apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo
          volumeMounts:
            - name: mongo
              mountPath: /data/db
      volumes:
        - name: mongo
          hostPath: 
            path: /mnt/mongo
            type: DirectoryOrCreate
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: mongo
  labels:
    name: mongo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo
          ports:
            - name: mongo
              containerPort: 27017
          volumeMounts:
            - name: mongo
              mountPath: /data/db
      volumes:
        - name: mongo
          persistentVolumeClaim:
            claimName: mongo
---
kind: Service
apiVersion: v1
metadata:
  name: mongo
spec:
  selector:
    app: mongo
  ports:
  - name: mongo
    port: 27017
    nodePort: 27017
  type: NodePort
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo
  labels: 
    name: mongo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
status: {}
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongo
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath: 
    path: "/var/lib/mongo"