---
kind: Service
apiVersion: v1
metadata:
  name: rocketchat
spec:
  selector:
    app: rocketchat
  ports:
    - protocol: TCP
      port: 33001
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocketchat
  labels:
    app: rocketchat
spec:
  selector:
    matchLabels:
      app: rocketchat
  replicas: 1
  template:
    metadata:
      labels:
        app: rocketchat
    spec:
      containers:
      - name: rocketchat
        image: rocketchat/rocket.chat:3.6.0
        env:
          - name: "PORT"
            value: "3000"
          - name: "ROOT_URL"
            value: "http://localhost:3000"
          - name: "MONGO_URL"
            value: "mongodb://mongo-0.default,mongo-1.default,mongo-2.mongo:30017/rocketchat"
          - name: "MONGO_OPLOG_URL"
            value: "mongodb://mongo-0.default,mongo-1.default,mongo-2.mongo:30017/local"
        ports:
        - containerPort: 3000